server:
  port: 5432
  servlet:
    context-path: /taller/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-205-232-84.compute-1.amazonaws.com:5432/d6l9vhjf9bgvjn
    username: hwaswzpzbdffnq
    password: e359695f462e7c6ac6113e8dfa366bbe9b4baf1e23ef5ad1f3a7c2089063d5aa
    platform: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
